name: workflow-deploy-starter-pom

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - "pom.xml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Trigger job-maven-deploy
  maven-deploy-pom:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.MAVEN_REPOSITORY_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Build with maven
        run: mvn --settings $GITHUB_WORKSPACE/.github/settings-github.xml --non-recursive --batch-mode clean package

      - name: Deploy to Github Package
        run: mvn --non-recursive --batch-mode deploy