name: workflow-deploy-starter-web

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - "starter-web/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Trigger job-maven-deploy
  maven-deploy:
    # Run after workflow-deploy-starter-pom
    # Run if workflow-deploy-starter-pom is not triggered
    # Run if pull request is merged
    needs: workflow-deploy-starter-pom
    if: github.event.pull_request.merged == true && always() && !failure() && !cancelled()
    uses: ./.github/workflows/job-maven-deploy-module.yml
    # To pass named inputs to a called workflow
    with:
      MODULE: starter-web
    secrets: inherit